services:
  app:
    image: ghcr.io/koshikai/koshikai:latest
    container_name: koshikai-app
    restart: always
    ports:
      - "3002:3000"
    env_file:
      - .env.prod
    environment:
      - NODE_ENV=production
